/**
 * Every route this application actually has.
 *
 * Read from the filesystem rather than from a list somebody maintains — the whole point of the
 * questions page is that it reports what is there rather than what a document says is there, and a
 * hand-kept list of routes would put the same fiction one layer down.
 */
import { readdirSync, existsSync } from 'node:fs';
import { EVERY_PAGE } from './every-page';
import { join } from 'node:path';

/**
 * Walk `src/app` and collect every folder that has a page.
 *
 * Dynamic segments (`[token]`) are kept as their literal folder name and also as their parent, so
 * `/customer/[token]` makes `/customer` resolvable — which is right, because the design names the
 * customer page and the fact that it needs a token is not the owner's question.
 */
export function routesInApp(root = join(process.cwd(), 'src/app')): Set<string> {
  const found = new Set<string>();

  const walk = (dir: string, path: string) => {
    if (existsSync(join(dir, 'page.tsx')) || existsSync(join(dir, 'page.ts'))) {
      found.add(path === '' ? '/' : path);
    }
    let entries: string[] = [];
    try {
      entries = readdirSync(dir, { withFileTypes: true }).filter(e => e.isDirectory()).map(e => e.name);
    } catch {
      return;
    }
    for (const name of entries) {
      /* Route groups in brackets that are not dynamic segments do not appear in the address. */
      if (name.startsWith('@') || name === 'api') continue;
      const isDynamic = name.startsWith('[');
      const next = isDynamic ? path : `${path}/${name}`;
      walk(join(dir, name), next);
      if (isDynamic) found.add(path === '' ? '/' : path);
    }
  };

  walk(root, '');
  return found;
}

/**
 * The same list, from the generated module rather than from the disk — and the one to use.
 *
 * ── The fault this exists to fix ─────────────────────────────────────────────────────────────────
 *
 * `routesInApp` above walks `src/app` with `readdirSync`. That is exactly right when something runs
 * in the repo: a test, a script, the build. It is wrong in the one place it was actually being
 * used — `/questions`, which is `force-dynamic` and therefore runs inside a serverless function on
 * every request, where **`src/` does not exist**. Next deploys compiled output, not source.
 *
 * So the walk found nothing, the set came back empty, and every question read as a gap. Measured on
 * 26 September, not guessed:
 *
 *     in the repo    79 routes → 93 of 96 questions answered
 *     in production   0 routes →  0 of 96 answered, 93 "have no screen behind them yet"
 *
 * The page whose whole job is to report honestly what the product can do had been telling Kris,
 * live, that it could do almost nothing. Every test passed throughout, because every test runs in
 * the repo. That is the failure this codebase keeps meeting from a new direction: a check that is
 * true where it is checked and false where it runs.
 *
 * `EVERY_PAGE` is generated by `scripts/reachable.mjs` and COMPILED IN, so it is the same list in
 * both places. `tests/reachable.test.ts` regenerates it and fails the build if it has gone stale.
 *
 * `routesInApp` is kept, not deleted: it is the honest answer in the repo and it is what generates
 * the module in the first place. Two functions on purpose — one that reads the disk, one that works
 * where there is no disk to read.
 */
export function routesInProduct(): Set<string> {
  return new Set(EVERY_PAGE.map(p => p.route));
}
