import { redirect } from 'next/navigation';
import { and, eq } from 'drizzle-orm';
import { db, schema } from '@/db';
import { getCurrentUser } from '@/lib/auth';
import { Shell } from '@/components/ui';
import { renderMarkdown } from '@/lib/markdown';
import { approveBoardOutput } from '@/app/period/actions';

export const dynamic = 'force-dynamic';

export default async function Board({ params }: { params: Promise<{ periodId: string }> }) {
  const { periodId } = await params;
  const user = await getCurrentUser(); if (!user) redirect('/signin');
  const periods = await db.select().from(schema.periods).where(and(eq(schema.periods.id, periodId), eq(schema.periods.tenantId, user.tenantId)));
  const period = periods[0];
  if (!period) return <Shell title="Not found"><p>No such period.</p></Shell>;
  const bos = await db.select().from(schema.boardOutputs).where(eq(schema.boardOutputs.periodId, periodId));
  const bo = bos[0];
  return (
    <Shell title={`Board output — ${period.period}`} subtitle={bo ? `Generated by ${bo.generatedBy} · ${bo.approvedBy ? `approved by ${bo.approvedBy}` : 'awaiting approval'}` : 'Not generated yet'}>
      {bo ? (
        <>
          <div
            className="rounded-lg border border-ink/10 bg-white p-6 text-sm leading-6 [&_h1]:mt-0 [&_h1]:font-serif [&_h1]:text-xl [&_h1]:font-bold [&_h1]:text-ink [&_h2]:mt-6 [&_h2]:font-serif [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-ink [&_h2]:first:mt-0 [&_p]:mt-3 [&_p]:first:mt-0 [&_strong]:font-semibold [&_strong]:text-ink [&_em]:text-ink-light [&_ul]:mt-2 [&_ul]:list-disc [&_ul]:pl-5 [&_li]:mt-1"
            dangerouslySetInnerHTML={{ __html: renderMarkdown(bo.markdown) }}
          />
          {!bo.approvedBy && user.access === 'full' && (
            <form action={approveBoardOutput} className="mt-4"><input type="hidden" name="periodId" value={periodId} />
              <button className="rounded-lg bg-rust px-5 py-2 text-white hover:bg-rust-dark">Approve for the board</button></form>
          )}
        </>
      ) : <p>Lock the period from the executive summary to generate it.</p>}
    </Shell>
  );
}
