import { redirect } from 'next/navigation';
import { and, eq } from 'drizzle-orm';
import { db, schema } from '@/db';
import { getCurrentUser } from '@/lib/auth';
import { Shell } from '@/components/ui';
import { approveBoardOutput } from '@/app/period/actions';

export const dynamic = 'force-dynamic';

export default async function Board({ params }: { params: Promise<{ periodId: string }> }) {
  const { periodId } = await params;
  const user = await getCurrentUser(); if (!user) redirect('/signin');
  const periods = await db.select().from(schema.periods).where(and(eq(schema.periods.id, periodId), eq(schema.periods.tenantId, user.tenantId)));
  const period = periods[0];
  if (!period) return <Shell title="Not found"><p>No such period.</p></Shell>;
  const bos = await db.select().from(schema.boardOutputs).where(eq(schema.boardOutputs.periodId, periodId));
  const bo = bos[0];
  return (
    <Shell title={`Board output — ${period.period}`} subtitle={bo ? `Generated by ${bo.generatedBy} · ${bo.approvedBy ? `approved by ${bo.approvedBy}` : 'awaiting approval'}` : 'Not generated yet'}>
      {bo ? (
        <>
          <pre className="whitespace-pre-wrap rounded-lg border bg-white p-6 font-sans text-sm leading-6">{bo.markdown}</pre>
          {!bo.approvedBy && user.access === 'full' && (
            <form action={approveBoardOutput} className="mt-4"><input type="hidden" name="periodId" value={periodId} />
              <button className="rounded-lg bg-slate-900 px-5 py-2 text-white hover:bg-slate-700">Approve for the board</button></form>
          )}
        </>
      ) : <p>Lock the period from the executive summary to generate it.</p>}
    </Shell>
  );
}
